runtime: python311
service: default

env_variables:
  GOOGLE_CLOUD_PROJECT: "alert-arbor-468516-g5"
  GOOGLE_CLOUD_LOCATION: "asia-northeast1"
  UPLOAD_DIR: "/tmp/uploads"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

instance_class: F1
