services:
  lambda-backend:
    image: food-analyzer-backend-lambda:local
    build:
      context: .
      dockerfile: app/Dockerfile
      target: aws_dev_service
    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT:-}
      GOOGLE_CLOUD_LOCATION: ${GOOGLE_CLOUD_LOCATION:-ap-northeast-1}
      GOOGLE_CSE_ID: ${GOOGLE_CSE_ID:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      INGREDIENTS_PROVIDER: ${INGREDIENTS_PROVIDER:-gemini}
      DEFAULT_MODEL: ${DEFAULT_MODEL:-gemini-2.5-pro}
      DEFAULT_OPENAI_MODEL: ${DEFAULT_OPENAI_MODEL:-gpt-4o}
      RAG_ARTIFACTS_DIR: ${RAG_ARTIFACTS_DIR:-/var/task/mmfood-rag/artifacts}
      UPLOAD_DIR: ${UPLOAD_DIR:-/tmp/uploads}
    ports:
      - "9000:8080"
    # Lambda runtime listens on 8080; exposing 9000 outside for curl tests
    restart: unless-stopped
