runtime: nodejs20
service: frontend

handlers:
  - url: /(.*\..+)$
    static_files: dist/food-analyzer-ui/\1
    upload: dist/food-analyzer-ui/(.*\..+)$
    secure: always

  - url: /.*
    static_files: dist/food-analyzer-ui/index.html
    upload: dist/food-analyzer-ui/index.html
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 1

instance_class: F1
